[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
